windows: allow static linking with LIBSLIRP_STATIC macro
When the macro is defined it will help to link with libslirp statically.
Otherwise, dllimport attribute is added with function symbols and linker
errors are shown as following for static linking.

undefined reference to `__imp_slirp_input'
undefined reference to `__imp_slirp_cleanup'
undefined reference to `__imp_slirp_remove_hostfwd'
etc.